apiVersion: unum.cloud/v1alpha1
kind: UStore
metadata:
  labels:
    app.kubernetes.io/name: ustore
    app.kubernetes.io/instance: ustore-sample-udisk
    app.kubernetes.io/part-of: ustore-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ustore-operator
  name: ustore-sample-udisk
spec:
  dbServicePort: 38709
  dbType: "udisk"
  dbConfigMapName: "sample-config-udisk"
  memoryLimit: "1Gi"
  concurrencyLimit: "1"
  volumes:
    - size: 10Gi
      accessMode: ReadWriteOnce
      mountPath: /mnt/disk1/
